// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

// Begin prologue.
//
//
// End prologue.

#include "ImageEntity-odb.hxx"

#include <odb/cache-traits.hxx>

#include <odb/mysql/mysql.hxx>
#include <odb/mysql/traits.hxx>
#include <odb/mysql/database.hxx>
#include <odb/mysql/transaction.hxx>
#include <odb/mysql/connection.hxx>
#include <odb/mysql/statement.hxx>
#include <odb/mysql/statement-cache.hxx>
#include <odb/mysql/object-statements.hxx>
#include <odb/mysql/container-statements.hxx>
#include <odb/mysql/exceptions.hxx>
#include <odb/mysql/result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // ImageEntity
  //

  struct access::object_traits< ::ImageEntity >::container_statement_cache_type
  {
    container_statement_cache_type (mysql::connection&)
    {
    }
  };

  const mysql::query_column<
    mysql::value_traits< long unsigned int, unsigned long long, mysql::id_ulonglong >::query_type,
    mysql::id_ulonglong>
  access::object_traits< ::ImageEntity >::query_type::id (
    "`ImageEntity`.`id`");

  const mysql::query_column<
    mysql::value_traits< ::std::string, details::buffer, mysql::id_string >::query_type,
    mysql::id_string>
  access::object_traits< ::ImageEntity >::query_type::name (
    "`ImageEntity`.`name`");

  const mysql::query_column<
    mysql::value_traits< ::std::string, details::buffer, mysql::id_string >::query_type,
    mysql::id_string>
  access::object_traits< ::ImageEntity >::query_type::study (
    "`ImageEntity`.`study`");

  const mysql::query_column<
    mysql::value_traits< int, int, mysql::id_long >::query_type,
    mysql::id_long>
  access::object_traits< ::ImageEntity >::query_type::measureid (
    "`ImageEntity`.`measureid`");

  const mysql::query_column<
    mysql::value_traits< int, int, mysql::id_long >::query_type,
    mysql::id_long>
  access::object_traits< ::ImageEntity >::query_type::localid (
    "`ImageEntity`.`localid`");

  const mysql::query_column<
    mysql::value_traits< double, double, mysql::id_double >::query_type,
    mysql::id_double>
  access::object_traits< ::ImageEntity >::query_type::value (
    "`ImageEntity`.`value`");

  const mysql::query_column<
    mysql::value_traits< double, double, mysql::id_double >::query_type,
    mysql::id_double>
  access::object_traits< ::ImageEntity >::query_type::lambda (
    "`ImageEntity`.`lambda`");

  const mysql::query_column<
    mysql::value_traits< int, int, mysql::id_long >::query_type,
    mysql::id_long>
  access::object_traits< ::ImageEntity >::query_type::expid (
    "`ImageEntity`.`expid`");

  const mysql::query_column<
    mysql::value_traits< int, int, mysql::id_long >::query_type,
    mysql::id_long>
  access::object_traits< ::ImageEntity >::query_type::generation (
    "`ImageEntity`.`generation`");

  const mysql::query_column<
    mysql::value_traits< int, int, mysql::id_long >::query_type,
    mysql::id_long>
  access::object_traits< ::ImageEntity >::query_type::slice (
    "`ImageEntity`.`slice`");

  const char* const access::object_traits< ::ImageEntity >::persist_statement =
  "INSERT INTO `ImageEntity` ("
  "`ImageEntity`.`id`,"
  "`ImageEntity`.`name`,"
  "`ImageEntity`.`study`,"
  "`ImageEntity`.`measureid`,"
  "`ImageEntity`.`localid`,"
  "`ImageEntity`.`value`,"
  "`ImageEntity`.`lambda`,"
  "`ImageEntity`.`expid`,"
  "`ImageEntity`.`generation`,"
  "`ImageEntity`.`slice`"
  ") VALUES (?,?,?,?,?,?,?,?,?,?)";

  const char* const access::object_traits< ::ImageEntity >::find_statement =
  "SELECT "
  "`ImageEntity`.`id`,"
  "`ImageEntity`.`name`,"
  "`ImageEntity`.`study`,"
  "`ImageEntity`.`measureid`,"
  "`ImageEntity`.`localid`,"
  "`ImageEntity`.`value`,"
  "`ImageEntity`.`lambda`,"
  "`ImageEntity`.`expid`,"
  "`ImageEntity`.`generation`,"
  "`ImageEntity`.`slice`"
  " FROM `ImageEntity`"
  " WHERE `ImageEntity`.`id` = ?";

  const char* const access::object_traits< ::ImageEntity >::update_statement =
  "UPDATE `ImageEntity` SET "
  "`ImageEntity`.`id` = ?,"
  "`ImageEntity`.`name` = ?,"
  "`ImageEntity`.`study` = ?,"
  "`ImageEntity`.`measureid` = ?,"
  "`ImageEntity`.`localid` = ?,"
  "`ImageEntity`.`value` = ?,"
  "`ImageEntity`.`lambda` = ?,"
  "`ImageEntity`.`expid` = ?,"
  "`ImageEntity`.`generation` = ?,"
  "`ImageEntity`.`slice` = ?"
  " WHERE `ImageEntity`.`id` = ?";

  const char* const access::object_traits< ::ImageEntity >::erase_statement =
  "DELETE FROM `ImageEntity`"
  " WHERE `ImageEntity`.`id` = ?";

  const char* const access::object_traits< ::ImageEntity >::query_clause =
  "SELECT "
  "`ImageEntity`.`id`,"
  "`ImageEntity`.`name`,"
  "`ImageEntity`.`study`,"
  "`ImageEntity`.`measureid`,"
  "`ImageEntity`.`localid`,"
  "`ImageEntity`.`value`,"
  "`ImageEntity`.`lambda`,"
  "`ImageEntity`.`expid`,"
  "`ImageEntity`.`generation`,"
  "`ImageEntity`.`slice`"
  " FROM `ImageEntity`"
  " ";

  access::object_traits< ::ImageEntity >::id_type
  access::object_traits< ::ImageEntity >::
  id (const image_type& i)
  {
    id_type id;
    mysql::value_traits<
        long unsigned int,
        unsigned long long,
        mysql::id_ulonglong >::set_value (
      id, i.id_value, i.id_null);

    return id;
  }

  void access::object_traits< ::ImageEntity >::
  grow (image_type& i, my_bool* e)
  {
    bool grew (false);

    // id_
    //
    e[0UL] = 0;

    // name_
    //
    if (e[1UL])
    {
      i.name_value.capacity (i.name_size);
      grew = true;
    }

    // study_
    //
    if (e[2UL])
    {
      i.study_value.capacity (i.study_size);
      grew = true;
    }

    // measureid_
    //
    e[3UL] = 0;

    // localid_
    //
    e[4UL] = 0;

    // value_
    //
    e[5UL] = 0;

    // lambda_
    //
    e[6UL] = 0;

    // expid_
    //
    e[7UL] = 0;

    // generation_
    //
    e[8UL] = 0;

    // slice_
    //
    e[9UL] = 0;

    if (grew)
      i.version++;
  }

  void access::object_traits< ::ImageEntity >::
  bind (MYSQL_BIND* b, image_type& i, bool out)
  {
    ODB_POTENTIALLY_UNUSED (out);

    std::size_t n (0);

    // id_
    //
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
    n++;

    // name_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.name_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.name_value.capacity ());
    b[n].length = &i.name_size;
    b[n].is_null = &i.name_null;
    n++;

    // study_
    //
    b[n].buffer_type = MYSQL_TYPE_STRING;
    b[n].buffer = i.study_value.data ();
    b[n].buffer_length = static_cast<unsigned long> (
      i.study_value.capacity ());
    b[n].length = &i.study_size;
    b[n].is_null = &i.study_null;
    n++;

    // measureid_
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.measureid_value;
    b[n].is_null = &i.measureid_null;
    n++;

    // localid_
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.localid_value;
    b[n].is_null = &i.localid_null;
    n++;

    // value_
    //
    b[n].buffer_type = MYSQL_TYPE_DOUBLE;
    b[n].buffer = &i.value_value;
    b[n].is_null = &i.value_null;
    n++;

    // lambda_
    //
    b[n].buffer_type = MYSQL_TYPE_DOUBLE;
    b[n].buffer = &i.lambda_value;
    b[n].is_null = &i.lambda_null;
    n++;

    // expid_
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.expid_value;
    b[n].is_null = &i.expid_null;
    n++;

    // generation_
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.generation_value;
    b[n].is_null = &i.generation_null;
    n++;

    // slice_
    //
    b[n].buffer_type = MYSQL_TYPE_LONG;
    b[n].is_unsigned = 0;
    b[n].buffer = &i.slice_value;
    b[n].is_null = &i.slice_null;
    n++;
  }

  void access::object_traits< ::ImageEntity >::
  bind (MYSQL_BIND* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].buffer_type = MYSQL_TYPE_LONGLONG;
    b[n].is_unsigned = 1;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  void access::object_traits< ::ImageEntity >::
  init (image_type& i, const object_type& o)
  {
    bool grew (false);

    // id_
    //
    {
      bool is_null;
      mysql::value_traits<
          long unsigned int,
          unsigned long long,
          mysql::id_ulonglong >::set_image (
        i.id_value, is_null, o.id_);
      i.id_null = is_null;
    }

    // name_
    //
    {
      bool is_null;
      std::size_t size (0);
      std::size_t cap (i.name_value.capacity ());
      mysql::value_traits<
          ::std::string,
          details::buffer,
          mysql::id_string >::set_image (
        i.name_value,
        size,
        is_null,
        o.name_);
      i.name_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.name_value.capacity ());
      i.name_null = is_null;
    }

    // study_
    //
    {
      bool is_null;
      std::size_t size (0);
      std::size_t cap (i.study_value.capacity ());
      mysql::value_traits<
          ::std::string,
          details::buffer,
          mysql::id_string >::set_image (
        i.study_value,
        size,
        is_null,
        o.study_);
      i.study_size = static_cast<unsigned long> (size);
      grew = grew || (cap != i.study_value.capacity ());
      i.study_null = is_null;
    }

    // measureid_
    //
    {
      bool is_null;
      mysql::value_traits<
          int,
          int,
          mysql::id_long >::set_image (
        i.measureid_value, is_null, o.measureid_);
      i.measureid_null = is_null;
    }

    // localid_
    //
    {
      bool is_null;
      mysql::value_traits<
          int,
          int,
          mysql::id_long >::set_image (
        i.localid_value, is_null, o.localid_);
      i.localid_null = is_null;
    }

    // value_
    //
    {
      bool is_null;
      mysql::value_traits<
          double,
          double,
          mysql::id_double >::set_image (
        i.value_value, is_null, o.value_);
      i.value_null = is_null;
    }

    // lambda_
    //
    {
      bool is_null;
      mysql::value_traits<
          double,
          double,
          mysql::id_double >::set_image (
        i.lambda_value, is_null, o.lambda_);
      i.lambda_null = is_null;
    }

    // expid_
    //
    {
      bool is_null;
      mysql::value_traits<
          int,
          int,
          mysql::id_long >::set_image (
        i.expid_value, is_null, o.expid_);
      i.expid_null = is_null;
    }

    // generation_
    //
    {
      bool is_null;
      mysql::value_traits<
          int,
          int,
          mysql::id_long >::set_image (
        i.generation_value, is_null, o.generation_);
      i.generation_null = is_null;
    }

    // slice_
    //
    {
      bool is_null;
      mysql::value_traits<
          int,
          int,
          mysql::id_long >::set_image (
        i.slice_value, is_null, o.slice_);
      i.slice_null = is_null;
    }

    if (grew)
      i.version++;
  }

  void access::object_traits< ::ImageEntity >::
  init (object_type& o, const image_type& i, database& db)
  {
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    mysql::value_traits<
        long unsigned int,
        unsigned long long,
        mysql::id_ulonglong >::set_value (
      o.id_, i.id_value, i.id_null);

    // name_
    //
    mysql::value_traits<
        ::std::string,
        details::buffer,
        mysql::id_string >::set_value (
      o.name_,
      i.name_value,
      i.name_size,
      i.name_null);

    // study_
    //
    mysql::value_traits<
        ::std::string,
        details::buffer,
        mysql::id_string >::set_value (
      o.study_,
      i.study_value,
      i.study_size,
      i.study_null);

    // measureid_
    //
    mysql::value_traits<
        int,
        int,
        mysql::id_long >::set_value (
      o.measureid_, i.measureid_value, i.measureid_null);

    // localid_
    //
    mysql::value_traits<
        int,
        int,
        mysql::id_long >::set_value (
      o.localid_, i.localid_value, i.localid_null);

    // value_
    //
    mysql::value_traits<
        double,
        double,
        mysql::id_double >::set_value (
      o.value_, i.value_value, i.value_null);

    // lambda_
    //
    mysql::value_traits<
        double,
        double,
        mysql::id_double >::set_value (
      o.lambda_, i.lambda_value, i.lambda_null);

    // expid_
    //
    mysql::value_traits<
        int,
        int,
        mysql::id_long >::set_value (
      o.expid_, i.expid_value, i.expid_null);

    // generation_
    //
    mysql::value_traits<
        int,
        int,
        mysql::id_long >::set_value (
      o.generation_, i.generation_value, i.generation_null);

    // slice_
    //
    mysql::value_traits<
        int,
        int,
        mysql::id_long >::set_value (
      o.slice_, i.slice_value, i.slice_null);
  }

  void access::object_traits< ::ImageEntity >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null;
      mysql::value_traits<
          long unsigned int,
          unsigned long long,
          mysql::id_ulonglong >::set_image (
        i.id_value, is_null, id);
      i.id_null = is_null;
    }
  }

  void access::object_traits< ::ImageEntity >::
  persist (database&, object_type& obj)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());
    image_type& im (sts.image ());
    binding& imb (sts.in_image_binding ());

    obj.id_ = 0;
    init (im, obj);

    if (im.version != sts.in_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, false);
      sts.in_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    obj.id_ = static_cast<id_type> (st.id ());
  }

  void access::object_traits< ::ImageEntity >::
  update (database&, const object_type& obj)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, obj.id_);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.in_image_binding ());
    init (im, obj);

    if (im.version != sts.in_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, false);
      sts.in_image_version (im.version);
      imb.version++;
    }

    sts.update_statement ().execute ();
  }

  void access::object_traits< ::ImageEntity >::
  erase (database&, const id_type& id)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();
  }

  access::object_traits< ::ImageEntity >::pointer_type
  access::object_traits< ::ImageEntity >::
  find (database& db, const id_type& id)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());
    object_statements< object_type >::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory< object_type, pointer_type  >::create ());
    pointer_traits< pointer_type >::guard pg (p);
    pointer_cache_traits< pointer_type >::insert_guard ig (
      pointer_cache_traits< pointer_type >::insert (db, id, p));
    object_type& obj (pointer_traits< pointer_type >::get_ref (p));

    if (l.locked ())
    {
      init (obj, sts.image (), db);
      load_ (sts, obj);
      sts.load_delayed ();
      l.unlock ();
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits< ::ImageEntity >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());
    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());
    object_statements< object_type >::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, id))
        return false;
    }

    reference_cache_traits< object_type >::insert_guard ig (
      reference_cache_traits< object_type >::insert (db, id, obj));

    if (l.locked ())
    {
      init (obj, sts.image (), db);
      load_ (sts, obj);
      sts.load_delayed ();
      l.unlock ();
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    return true;
  }

  bool access::object_traits< ::ImageEntity >::
  find_ (mysql::object_statements< object_type >& sts, const id_type& id)
  {
    using namespace mysql;

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.out_image_binding ());

    if (im.version != sts.out_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, true);
      sts.out_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());
    st.execute ();
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      grow (im, sts.out_image_error ());

      if (im.version != sts.out_image_version ())
      {
        bind (imb.bind, im, true);
        sts.out_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    st.free_result ();
    return r != select_statement::no_data;
  }

  template<>
  result< access::object_traits< ::ImageEntity >::object_type >
  access::object_traits< ::ImageEntity >::
  query< access::object_traits< ::ImageEntity >::object_type > (
    database& db,
    const query_type& q)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());

    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());
    details::shared_ptr<select_statement> st;

    query_ (db, q, sts, st);

    details::shared_ptr<odb::result_impl<object_type> > r (
      new (details::shared) mysql::result_impl<object_type> (st, sts));
    return result<object_type> (r);
  }

  template<>
  result< const access::object_traits< ::ImageEntity >::object_type >
  access::object_traits< ::ImageEntity >::
  query< const access::object_traits< ::ImageEntity >::object_type > (
    database& db,
    const query_type& q)
  {
    using namespace mysql;

    connection& conn (mysql::transaction::current ().connection ());

    object_statements< object_type >& sts (
      conn.statement_cache ().find<object_type> ());
    details::shared_ptr<select_statement> st;

    query_ (db, q, sts, st);

    details::shared_ptr<odb::result_impl<const object_type> > r (
      new (details::shared) mysql::result_impl<const object_type> (st, sts));
    return result<const object_type> (r);
  }

  void
  access::object_traits< ::ImageEntity >::
  query_ (database&,
          const query_type& q,
          mysql::object_statements< object_type >& sts,details::shared_ptr<mysql::select_statement>& st)
  {
    using namespace mysql;

    image_type& im (sts.image ());
    binding& imb (sts.out_image_binding ());

    if (im.version != sts.out_image_version () || imb.version == 0)
    {
      bind (imb.bind, im, true);
      sts.out_image_version (im.version);
      imb.version++;
    }

    st.reset (new (details::shared) select_statement (
                sts.connection (),
                query_clause + q.clause (),
                q.parameters (),
                imb));
    st->execute ();
  }
}

// Begin epilogue.
//
//
// End epilogue.

#include <odb/post.hxx>
